### ISSUE TITLE
"REFACTOR: Moved most methods out of classes" Breaks prod

### ISSUE THREAD

**Issue by ccpandhare** [timmahrt/praatIO.js#2]
Hi,

`lib/index.js` attempts to import `IncorrectArgumentException` from `lib/textgrid.js`, which is no longer being exported after b8864c6 REFACTOR: Moved most methods out of classes

I would have simply submitted a PR to fix this, but I'm unaware of what all is affected by this.

**Comment by timmahrt** [comment]
Hello,
Sorry for the inconvenience.  I've fixed it.  I updated one of my tests to validate that the exception can be imported correctly.  A few other exceptions were also affected and I updated them too.

I don't have time at the moment to ensure that everything is being tested as it should be, so I wrote a kindof dumb test that just imports everything and ensures that nothing is undefined.

Thanks!

**Comment by ccpandhare** [comment]
Thank you so much for the super quick fix! It's really appreciated 😄
