### ISSUE TITLE
About TextGrid normal/short

### ISSUE THREAD

**Issue by jinjingzhong** [timmahrt/praatIO.js#4]
Hi, recently, I found this praatIO for my apps, it's really useful, but after I parsed and modified my TextGrid with praatIO, I could not find a serialization method for the NORMAL type TextGrid, the exists serializatin method is for SHORT type. the praatIO can recognize NORMAL/SHORT type TextGrid when parsing, Maybe there should be a function for recognizing different type when sirialization. 
Could you update for it? 
Best regards.

**Comment by timmahrt** [comment]
Hello jinjingzhong,
I recently had this request for my python praatIO library.  It's an easy fix and it is good to have.

I should have time to do it today or tomorrow.  I'll let you know once its released.  Thanks!
Tim

**Comment by timmahrt** [comment]
I've published praatio.js version 2.2.0

`let longText = serializeTextgrid(tg, null, null, null, false);` will output a textdump of a textgrid in normal format that can be saved to a file.

By default, serializeTextgrid(tg) will save to a short textgrid for backwards compatibility reasons.

If you notice any problems or have any questions, please let me know.  Thanks!

**Comment by jinjingzhong** [comment]
Thanks for updating, It is really helpful for me,thank you .

**Comment by timmahrt** [comment]
I'll close this issue for now.  If you have other questions, feel free to reopen or make a new issue.  Thanks!
